preload = /home/ryanmatsui/Downloads/heaven.png
wallpaper = HDMI-A-1,/home/ryanmatsui/Downloads/heaven.png
splash = false

wallpaper {
    monitor = 
    path = /home/ryanmatsui/Downloads/heaven.png
    fit_mode = cover
}
